apiVersion: apps/v1
kind: Deployment
metadata:
  name: giropops-v1
  labels:
    app: giropops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: giropops
  template:
    metadata:
      labels:
        app: giropops
      # passando informação para o cluster que o pod pode ser monitorado pelo prometheus
      annotations:
        # Vai começar a pegar informações automaticamente do container que está rodando na porta 8080
        prometheus.io/scrape: "true"
        # Porta que vai expor as métricas
        prometheus.io/port: "32111"
    spec:
      containers:
      - name: giropops
        image: linuxtips/nginx-prometheus-exporter:1.0.0
        env:
        - name: VERSION
          value: "1.0.0"
        ports:
        - containerPort: 80
        - containerPort: 32111
