apiVersion: v1
kind: Pod
metadata:
  name: pod-test
  labels:
    app: pod-test
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "32111"
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do echo "Hello World"; sleep 10; done']
    ports:
    - containerPort: 80
    - containerPort: 32111