apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  # vai dar permissão de administrador para o usuário admin-user
  apiGroup: rbac.authorization.k8s.io
  # Associando o usuário admin-user ao cluster-admin
  kind: ClusterRole
  name: cluster-admin
# é possível associar um usuário a um grupo de usuários ou a um serviço de conta
# Associando o service account admin-user ao clustr-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kube-system