apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
    - name: busybox
      image: busybox
      command: 
        - sleep
        - "3600"
      # Especificando um volume para o container
      volumeMounts:
        # Aonde o volume será montado dentro do container
        - mountPath: /giropops
        # Nome do volume
          name: giropops-dir
  #Definindo um volume vazio
  volumes:
      # Nome do volume vazio
    - name: giropops-dir
      # Tipo do volume vazio
      emptyDir: {}
