apiVersion: v1
kind: Pod
metadata:
  name: teste-secret-env
  namespace: default
spec:
  containers:
    - image: busybox
      name: busy-secret-env
      command:
        - sleep
        - "3600"
      env:
      - name: MEU_USERNAME
        #Valor de algum lugar, ou seja, de uma secretkeyref
        valueFrom:
          # Valor da chave user do secret my-literal-secret que ser치 usado na vari치vel MEU_USERNAME
          secretKeyRef:
            name: my-literal-secret
            # Chave do secret my-literal-secret que ser치 usado na vari치vel MEU_USERNAME
            key: user
      - name: MEU_PASSWORD
        valueFrom:
          secretKeyRef:
            name: my-literal-secret
            key: password
