apiVersion: v1
kind: Pod
metadata:
  name: busybox-configmap
  namespace: default
spec:
  containers:
    - image: busybox
      name: busy-configmap
      command:
       - sleep
       - "3600"
      envFrom:
      # traz todas as chaves do configmap cores-frutas
      - configMapRef:
          name: cores-frutas
