apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /giropops
      name: primeiro-emptydir
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.5"
      requests:
        memory: "64Mi"
        cpu: "0.3"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - emptyDir:
      sizeLimit: "256Mi"
    name: primeiro-emptydir
