apiVersion: v1
kind: Pod
metadata:
  name: zipkin
  labels:
    app: zipkin
spec: 
  containers:
  - name: zipkin
    image: openzipkin/zipkin
    ports:
    - containerPort: 9411
      protocol: TCP
    env:
    - name: STORAGE_TYPE
      value: mem
    - name: JAVA_OPTS
      value: -Xms256m -Xmx256m
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"

---

apiVersion: v1
kind: Service
metadata:
  name: svc-zipkin
spec:
  type: NodePort
  selector:
    app: zipkin
  ports:
    - port: 9411
      nodePort: 30000
      targetPort: 9411
      protocol: TCP
