apiVersion: apps/v1
kind: Deployment
metadata:
  #annotations:
  generation: 1
  name: meu-nginx
  labels:
    run: nginx
  namespace: default

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate  
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Always
        port:
        - containerPort: 80
          protocol: TCP
